databaseChangeLog:

  - changeSet:
      id: currency-table-init
      author: alexander.severgin
      changes:
        - createTable:
            tableName: currency
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
                  autoIncrement: true
              - column:
                  name: code
                  type: varchar(3)

  - changeSet:
      id: customer-table-init
      author: alexander.severgin
      changes:
        - createTable:
            tableName: customer
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
                  autoIncrement: true
              - column:
                  name: name
                  type: varchar(250)
              - column:
                  name: surname
                  type: varchar(250)

  - changeSet:
      id: user-table-init
      author: alexander.severgin
      changes:
        - createTable:
            tableName: user
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
                  autoIncrement: true
              - column:
                  name: display_name
                  type: varchar(350)

  - changeSet:
      id: offer-table-init
      author: alexander.severgin
      changes:
        - createTable:
            tableName: offer
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
                  autoIncrement: true
              - column:
                  name: price
                  type: decimal(7,2)
              - column:
                  name: currency_id
                  type: bigint
              - column:
                  name: offer_key
                  type: varchar(100)
              - column:
                  name: status
                  type: varchar(250)
              - column:
                  name: created_date_time
                  type: timestamp
              - column:
                  name: expiry_date_time
                  type: timestamp
              - column:
                  name: description
                  type: text
              - column:
                  name: customer_id
                  type: bigint
              - column:
                  name: responsible_manager_id
                  type: bigint

        - addForeignKeyConstraint:
            constraintName: fk_offer_currency
            baseColumnNames: currency_id
            baseTableName: offer
            referencedColumnNames: id
            referencedTableName: currency

        - addForeignKeyConstraint:
            constraintName: fk_offer_customer
            baseColumnNames: customer_id
            baseTableName: offer
            referencedColumnNames: id
            referencedTableName: customer

        - addForeignKeyConstraint:
            constraintName: fk_offer_responsible_manager
            baseColumnNames: responsible_manager_id
            baseTableName: offer
            referencedColumnNames: id
            referencedTableName: user